var catalyst = catalyst || {};
catalyst.yahtzee = catalyst.yahtzee || {};

catalyst.yahtzee.CONSTANTS = {
	NUMBER_DICE : 5,
	DICE_SIDES : 6,
	ACES_VALUE : 1,
	TWOS_VALUE : 2,
	THREES_VALUE : 3,
	FOURS_VALUE : 4,
	FIVES_VALUE : 5,
	SIXES_VALUE : 6,
	ACES : 'Aces',
	TWOS : 'Twos',
	THREES : 'Threes',
	FOURS : 'Fours',
	FIVES : 'Fives',
	SIXES : 'Sixes',
	UPPER_SUB : 'Sub Total',
	BONUS : 'Bonus',
	UPPER_TOTAL : 'Upper Total',
	THREE_KIND : 'Three of a Kind',
	FOUR_KIND : 'Four of a Kind',
	FULL_HOUSE : 'Full House',
	SMALL_STRAIGHT : 'Small Straight',
	LARGE_STRAIGHT : 'Large Straight',
	YAHTZEE : 'Yahtzee',
	CHANCE : 'Chance',
	YAHTZEE_BONUS : 'Yahtzee Bonus',
	LOWER_TOTAL : 'Lower Total',
	GRAND_TOTAL : 'Grand Total',

	ACES_SELECTOR : '#aces',
	TWOS_SELECTOR : '#twos',
	THREES_SELECTOR : '#threes',
	FOURS_SELECTOR : '#fours',
	FIVES_SELECTOR : '#fives',
	SIXES_SELECTOR : '#sixes',
	UPPER_SUB_SELECTOR : '#subTotalUpper',
	BONUS_SELECTOR : '#bonus',
	UPPER_TOTAL_SELECTOR : '.totalUpper',
	THREE_KIND_SELECTOR : '#threeOfAKind',
	FOUR_KIND_SELECTOR : '#fourOfAKind',
	FULL_HOUSE_SELECTOR : '#fullHouse',
	SMALL_STRAIGHT_SELECTOR : '#smallStraight',
	LARGE_STRAIGHT_SELECTOR : '#largeStraight',
	YAHTZEE_SELECTOR : '#yahtzee',
	CHANCE_SELECTOR : '#chance',
	YAHTZEE_BONUS_SELECTOR : '#yahtzeeBonus',
	LOWER_TOTAL_SELECTOR : '#totalLower',
	GRAND_TOTAL_SELECTOR : '#grandTotal',

	FULL_HOUSE_SCORE : 25,
	SMALL_STRAIGHT_SCORE : 30,
	LARGE_STRAIGHT_SCORE : 40,
	YAHTZEE_SCORE : 50,
	YAHTZEE_BONUS_SCORE : 100,

	SMALL_STRAIGHT_LENGTH : 4,
	LARGE_STRAIGHT_LENGTH : 5,

	BONUS_BOUND : 63


}
